Remove is_tracking field
Kukanani/vision_msgs_proposal pull request #50
Opened 2020-12-20 22:47 UTC by Kukanani

This field does not seem useful, and we are not aware of anyone using it at this time. `VisionInfo` is probably a better place for this information anyway, if it were needed. 

See #47 for earlier discussions.

2020-12-21 09:29 UTC, mintar requested changes

2020-12-21 09:29 UTC, mintar commented on msg/Detection2D.msg
>  # If you set this field, be sure to also set is_tracking to True.
This line (the comment mentioning is_tracking) should be removed.

2020-12-21 09:29 UTC, mintar commented on msg/Detection3D.msg
>  # If you set this field, be sure to also set is_tracking to True.
This line should be removed as well (see above).

2021-01-02 22:03 UTC, Kukanani commented
Thanks for the review! Merging.

2021-01-02 22:03 UTC, merged